### ISSUE TITLE
Hard-coded CSS mangles RTL layouts

### ISSUE THREAD

**Issue by FGasper** [xtermjs/xterm.js#1330]
#701 documents ongoing work toward full support for RTL; however, a separate, related issue is that `xterm.css` includes hard-coded `left` and `right` rules which don’t display correctly on RTL pages:

![image](https://user-images.githubusercontent.com/844867/37313477-c4040944-2625-11e8-83c1-feb492273676.png)

## Details
- Browser and browser version: FF/Mac and Chrome/Mac, current versions
- OS version: macOS High Sierra
- xterm.js version: 3.2.0

### Steps to reproduce

1. Set `dir="rtl"` on the demo’s index.html.
2. Load the demo.

OBSERVE: The page appears to be blank because everything is -9999em to the left.
EXPECTED: The CSS shouldn’t assume left-to-right document layout.

**Comment by FGasper** [comment]
Is there any motion on this? It’s going to be an impediment for our implementation. We can do a local patch, but I would think the fix is desirable outside our own code.

Thanks!

**Comment by Tyriar** [comment]
@FGasper just responded, this should make it into 3.3. I had a huge backlog of notifications that I'm nearly through now.

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1350

**Comment by FGasper** [comment]
@Tyriar This is broken again in v3.3.0.

![image](https://user-images.githubusercontent.com/844867/38815986-1fbdccb8-4163-11e8-849f-e5c7ac4574c3.png)

**Comment by FGasper** [comment]
Looks like the fix was bad … :-/ I repeated the testing with b27d5bb08dba9589721d37fc34b04a1fa5437d75 and still see the issue.

**Comment by FGasper** [comment]
@Tyriar Rather than setting -9999px for the various elements that get that treatment, what about a combination of:

color: transparent;
background-color: transparent;
opacity: 0;
height: 0;
width: 0;
z-index: -9999

??

**Comment by Tyriar** [comment]
Do you mean this? https://github.com/xtermjs/xterm.js/blob/a3ce881897818d1c61476620e7d037717ca9a68f/src/xterm.css#L125

**Comment by FGasper** [comment]
@Tyriar That’s what I would have thought, but there’s no class on the element; the styles are directly on the element.

**Comment by Tyriar** [comment]
@FGasper there should be:

https://github.com/xtermjs/xterm.js/blob/a3ce881897818d1c61476620e7d037717ca9a68f/src/utils/CharMeasure.ts#L25-L28

**Comment by FGasper** [comment]
Yeah, I saw that. I wondered if I have an old version of the demo but have rebuilt and still see no class. Let me retry.

**Comment by FGasper** [comment]
OK. I had to manually blow away `demo/dist`.

(Does the build stack not check mtimes and rebuild resources as appropriate?)

**Comment by Tyriar** [comment]
@FGasper I only ever use `npm run watch` which I know completely rebuilds `lib/` at least.
