### ISSUE TITLE
IMEs are duplicating some characters on Edge/Chrome

### ISSUE THREAD

**Issue by Jandou6** [xtermjs/xterm.js#1527]
I run the xterm.js demo. Found, if use Microsoft Pinyin IME 
## Details
- Browser and browser version: Chrome66
- OS version: Win10, Win8
- xterm.js version: 3.2.0

### Steps to reproduce

1. Run demo in Window
2. use Microsoft Pinyin IME . And switch Chinese Mode ( use keyboard 【Shift】)
3. Input num key (0~9) .You will found It is hard to input.

**Comment by Tyriar** [comment]
@Jandou6 what about number input does not work as you're expecting?

**Comment by rebornix** [comment]
@Tyriar after I switch to Chinse IME and press any num key, the same number is inserted to the terminal twice.

**Comment by Tyriar** [comment]
Think this is fixed.

**Comment by ZxBing0066** [comment]
> Think this is fixed.

Please reopen this, this can still reproduce in the newest version.

A demo here: https://codesandbox.io/s/crimson-frost-s11ts?file=/src/index.js:0-267

Use Microsoft Pinyin number input to reproduce

```js
import { Terminal } from 'xterm';
import 'xterm/css/xterm.css';

const term = new Terminal();

term.open(document.getElementById('terminal'));
term.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')

term.onData(data => {
  console.log(data);
  term.write(data);
});
```
